workflows:
  ios-build:
    name: Build iOS IPA
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: ios/App/App.xcodeproj
        XCODE_SCHEME: App
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build ipa for distribution
        script: |
          cd ios/App
          xcodebuild -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            build
    artifacts:
      - ios/App/build/**/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com


